CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(250) NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(250),
    phone_number VARCHAR(14),
    balance DECIMAL(12, 2) NOT NULL,
    CONSTRAINT email_phone_cons CHECK (email IS NOT NULL or phone_number IS NOT NULL),
    CONSTRAINT positive_balance CHECK (balance >= 0.0)
)